changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bug fixes
      labels:
        - bug
    - title: Enhancements
      labels:
        - enhancement
    - title: Visuals
        - visuals
    - title: Readables
      labels:
        - readables
    - title: Sound
      labels:
        - sound
    - title: Performance
      labels:
        - performance
    - title: Gameplay
      labels:
        - gameplay
    - title: Housekeeping
      labels:
        - housekeeping
    - title: Other Changes
      labels:
        - "*"